# frozen_string_literal: true

module Decidim
  module ResourceBanks
    # Service that encapsulates all logic related to filtering resource_banks.
    class ResourceBankSearch < ParticipatorySpaceSearch
      def initialize(options = {})
        super(ResourceBank.all, options)
      end

      # We need to return the scope generated by the base_query method in the parent
      # class because it doesn't return it, only generates it. We need to do a PR on Decidim?
      def base_query
        super

        @scope
      end
    end
  end
end
